### ISSUE TITLE
Are millenniums allowed?

### ISSUE THREAD

**Issue by OtterSou** [IJMacD/rfc3339-iso8601#5]
On my copy of ISO 8601-1:2019, I don't see any mention of milleniums. Your table (specifically `2`) says it's allowed, but I don't think so.

**Comment by IJMacD** [comment]
Yes thank you for raising this issue.

I looked into it and I think I made an assumption based on § 5.2.2.2 Representations with reduced precision. Earlier drafts gave examples reducing precision down to centuries but gave no indication whether decades or millennia were supported.

I think it now says:

> either two, four or six digits may be omitted, the omission starting from the extreme right-hand side.

I think I'll need to update the diagram and table.

Thanks.

**Comment by Crissov** [comment]
Just for the record, [EDTF Level 2](https://www.loc.gov/standards/datetime/) in ISO 8601-2 supports stuff like `2XXX` (unspecified digits) and `Y2E3S1` (exponential year with significant digits) to represent any year in a particular millennium.
