### ISSUE TITLE
"This table is not exhaustive"?

### ISSUE THREAD

**Issue by ColtonIdle** [IJMacD/rfc3339-iso8601#6]
Does that only apply to the readme.md or does that apply to the actual website itself (macd.github.io/rfc3339-iso8601)

**Comment by IJMacD** [comment]
Hi Colton,

The message appears both on the repo's README and on the live site. It applies in both places.

There are thousands (if not millions) of possible combinations of numbers of decimal digits, upper and lower case etc. Multiplied by the number of possibilities when combining two DateTimes for ranges or a DateTime combined with the hundreds of possibilities of Periods (either way round).

It would not be practical or useful to try and enumerate many more theoretically possible combinations.

**Comment by ColtonIdle** [comment]
Thanks for clarifying that and excuse my ignorance. Thanks for teaching!
