### ISSUE TITLE
Should "%Y-%M-%DT%h:%m:%s.%uZ" be a valid RFC 3339 datetime?

### ISSUE THREAD

**Issue by dacut** [IJMacD/rfc3339-iso8601#7]
The equivalent format with the timezone split out is here:
https://github.com/IJMacD/rfc3339-iso8601/blob/master/src/formats/rfc.js#L33

And this is generated as an ISO format:

> %Y-%M-%DT%h:%m:%s.%uZ | 2021-07-27T14:20:32.556000Z |   | ✔️

I believe this is just an omission in the rfc.js file. A quick read of RFC 3339 doesn't mention anything prohibiting this combination.

Thanks! This is a valuable resource in the date/time format craziness!

**Comment by IJMacD** [comment]
Thank you for pointing this out. I believe you are correct, and it had just been unintentionally omitted.

I've added the missing line to rfc.js as well as the format from the original title of this issue as it too wasn't included. (But at least unlike the former case its prior omission wasn't misleading)
